version: "3"
services:

  # DATABASE
  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
          - "27017:27017"

  # BACK-END
  web-back:
    container_name: web-back
    build: ./backend
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb

  # FRONT-END
  web-front:
    container_name: web-front
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on: 
      - web-back